# Generated by Django 5.1.3 on 2024-11-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_remove_media_name_af_remove_media_name_ar_and_more'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255, null=True)),
                ('full_name_az', models.CharField(max_length=255, null=True)),
                ('full_name_ru', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255)),
                ('position_en', models.CharField(max_length=255, null=True)),
                ('position_az', models.CharField(max_length=255, null=True)),
                ('position_ru', models.CharField(max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, limit_choices_to={'type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_image', to='media.media')),
                ('social_media', models.ManyToManyField(blank=True, to='social.socialmedia')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
