# Generated by Django 5.1.3 on 2024-11-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='social_media',
        ),
        migrations.AddField(
            model_name='teammember',
            name='social_media',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
