# Generated by Django 5.1.3 on 2024-11-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_media_name_af_remove_media_name_ar_and_more'),
        ('team', '0002_remove_teammember_social_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='social_media',
        ),
        migrations.CreateModel(
            name='TeamSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon', models.ForeignKey(blank=True, limit_choices_to={'type': 'icon'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_social_icon', to='media.media')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='team.teammember')),
            ],
            options={
                'verbose_name': 'Team Social Media',
                'verbose_name_plural': 'Team Social Media Accounts',
            },
        ),
    ]
