# Generated by Django 5.1.3 on 2024-11-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_media_name_af_remove_media_name_ar_and_more'),
        ('team', '0003_remove_teammember_social_media_teamsocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_az', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, limit_choices_to={'type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='media.media')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
