# Generated by Django 5.1.3 on 2024-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='service.tag'),
        ),
    ]
