# Generated by Django 5.1.3 on 2024-11-29 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_remove_media_name_af_remove_media_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shi Studio', max_length=255)),
            ],
            options={
                'verbose_name': 'Company Name',
                'verbose_name_plural': 'Company Name',
            },
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField()),
                ('completed_projects', models.IntegerField()),
                ('ongoing_projects', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Work Status',
                'verbose_name_plural': 'Work Status',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField()),
                ('goal', models.TextField()),
                ('logo', models.ForeignKey(blank=True, limit_choices_to={'type': 'logo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
    ]
