# Generated by Django 5.1.3 on 2024-11-29 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_remove_media_name_af_remove_media_name_ar_and_more'),
        ('service', '0003_progress'),
        ('team', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_az', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_az', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('project_behance_url', models.URLField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('client', models.CharField(max_length=255)),
                ('client_en', models.CharField(max_length=255, null=True)),
                ('client_az', models.CharField(max_length=255, null=True)),
                ('client_ru', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255)),
                ('industry_en', models.CharField(max_length=255, null=True)),
                ('industry_az', models.CharField(max_length=255, null=True)),
                ('industry_ru', models.CharField(max_length=255, null=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_projects', to='team.teammember')),
                ('hover_image', models.ForeignKey(blank=True, limit_choices_to={'type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_hover_images', to='media.media')),
                ('image', models.ForeignKey(blank=True, limit_choices_to={'type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_images', to='media.media')),
                ('services', models.ManyToManyField(blank=True, related_name='projects', to='service.service')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_az', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='project.project')),
            ],
        ),
    ]
